# Generated by Django 4.2.3 on 2023-08-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vegeee', '0002_remove_recipe_cook_time_remove_recipe_prep_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_image',
            field=models.ImageField(upload_to='uploads'),
        ),
    ]
